<!DOCTYPE html>
<html lang="zh-CN">
    <head>
      <script type="module" src="/@vite/client"></script>

        <meta charset="UTF-8" />
        <link rel="icon" type="image/svg+xml" href="/app.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="/vconsole.min.js"></script>
        <title>PakePlus</title>
    </head>

    <body>
        <div id="app"></div>
        <script type="module" src="/src/main.ts?t=1765954611980"></script>
    </body>
</html>
